hash table
OasisDEX/automation-smartcontracts pull request #104
Opened 2022-07-27 12:01 UTC by halaprix

2022-07-28 13:13 UTC, rkrasiuk commented on contracts/AutomationBotAggregator.sol
> +    }
```suggestion
    function getTriggerHash(
        uint256 cdpId,
        bytes memory triggerData,
        address commandAddress
    ) private view returns (bytes32) {
        return keccak256(
            abi.encodePacked(cdpId, triggerData, serviceRegistry, commandAddress)
        );
    }
```

2022-07-28 13:13 UTC, rkrasiuk commented on contracts/AutomationBotAggregator.sol
> +                    AutomationBot(bot).addTrigger.selector,
```suggestion
                    bot.addTrigger.selector,
```

2022-07-28 13:13 UTC, rkrasiuk commented on contracts/AutomationBotAggregator.sol
> +                    AutomationBot(bot).removeTrigger.selector,
```suggestion
                    bot.removeTrigger.selector,
```

2022-07-28 13:13 UTC, rkrasiuk commented on contracts/AutomationBotAggregator.sol
> +                AutomationBot(bot).addTrigger.selector,
```suggestion
                bot.addTrigger.selector,
```

2022-07-29 10:48 UTC, adamskrodzki requested changes

2022-07-29 10:48 UTC, adamskrodzki commented on contracts/commands/CmBasicBuyCommand.sol
> +    function execute(
I believe instead of copy-pasting You can inherit and only override execute

2022-08-01 14:49 UTC, adamskrodzki approved these changes

2022-08-01 14:49 UTC, adamskrodzki commented on contracts/commands/CmBasicBuyCommand.sol
> +    function execute(
https://github.com/OasisDEX/automation-smartcontracts/pull/109

2022-08-01 14:50 UTC, adamskrodzki requested changes
https://github.com/OasisDEX/automation-smartcontracts/pull/109

2022-08-02 07:56 UTC, adamskrodzki requested changes
Add deployment script for this specific feature in:
https://github.com/OasisDEX/automation-smartcontracts/tree/dev/scripts/deployment

2022-08-02 08:02 UTC, halaprix commented
> Add deployment script for this specific feature in: https://github.com/OasisDEX/automation-smartcontracts/tree/dev/scripts/deployment

done : https://github.com/OasisDEX/automation-smartcontracts/pull/104/commits/4b1a3b16515af0024f1a18dea8a0a8042a54bba1

2022-08-02 08:02 UTC, rkrasiuk requested changes

2022-08-02 08:24 UTC, halaprix commented on contracts/commands/CmBaseMPACommand.sol
> +        uint256 BsPrice;
done

2022-08-02 08:24 UTC, halaprix commented on scripts/common/deploy-system.ts
> +    CmBasicBuyCommand,
https://github.com/OasisDEX/automation-smartcontracts/commit/4b1a3b16515af0024f1a18dea8a0a8042a54bba1

2022-08-02 08:52 UTC, adamskrodzki approved these changes

2022-08-02 09:31 UTC, rkrasiuk requested changes

2022-08-02 09:31 UTC, rkrasiuk commented on scripts/deployment/deploy-cm-basic-buy.ts
> +    await configureRegistryEntries(utils, system, utils.addresses as AddressRegistry, [])
add command hash to `overwrites` parameter

2022-08-02 09:31 UTC, rkrasiuk commented on scripts/deployment/deploy-cm-basic-sell.ts
> +    await configureRegistryEntries(utils, system, utils.addresses as AddressRegistry, [])
same here

2022-08-02 10:37 UTC, adamskrodzki approved these changes

2022-08-02 10:48 UTC, merged