[SC][UNISWAP3]Modify Executor in a way that It will enable exchange of DAI to ETH (unwrapped) In order for rebalancer to be able to call it directly
OasisDEX/automation-smartcontracts pull request #128
Opened 2022-09-02 10:36 UTC by halaprix

[[SC]Modify Executor in a way that It will enable exchange of DAI to ETH (unwrapped) In order for rebalancer to be able to call it directly](https://app.shortcut.com/oazo-apps/story/5706/sc-modify-executor-in-a-way-that-it-will-enable-exchange-of-dai-to-eth-unwrapped-in-order-for-rebalancer-to-be-able-to-call)

2022-09-05 10:40 UTC, adamskrodzki commented on contracts/AutomationExecutor.sol
> +            return (2**192 * (10**decimals)) / (uint256(sqrtPriceX96) * (uint256(sqrtPriceX96)));
no overflow risk here ?
how about 
`2**192/ (uint256(sqrtPriceX96) * (uint256(sqrtPriceX96))) * (10**decimals)`
?

2022-09-26 13:07 UTC, adamskrodzki requested changes

2022-09-27 11:39 UTC, halaprix commented on contracts/AutomationExecutor.sol
> +        bytes memory path = abi.encodePacked(tokenIn, uint24(fee), tokenOut);
irrelevant after change to `swapToEth` :)

2022-09-27 11:39 UTC, halaprix commented on contracts/AutomationExecutor.sol
> +    function getTick(address uniswapV3Pool, uint32 twapInterval)
we agreed to keep it after changing to `swapToEth`

2022-10-07 07:24 UTC, adamskrodzki approved these changes

2022-10-25 13:57 UTC, merged