[Sc][Research] Remove cdpId and triggerType from storage
OasisDEX/automation-smartcontracts pull request #131
Opened 2022-09-07 15:01 UTC by halaprix

[ Remove cdpId and triggerType from storage](https://app.shortcut.com/oazo-apps/story/5710/sc-reesearch-remove-cdpid-and-triggertype-from-triggers-data)

2022-09-28 08:18 UTC, halaprix commented
tasks are down - the need reworks that are not required at this point - they are commented out

2022-09-28 12:07 UTC, adamskrodzki requested changes

2022-09-28 12:07 UTC, adamskrodzki commented on contracts/AutomationBot.sol
> +                0x0000000000000000000000000000000000000000,
pass `coverageToken` here

2022-09-28 12:07 UTC, adamskrodzki commented on contracts/AutomationBot.sol
>          uint256 daiCoverage
add parameter `coverageToken`

2022-09-28 12:07 UTC, adamskrodzki commented on contracts/Emitter.sol
> +pragma solidity ^0.8.0;
this cannot be used without full security, delete it

2022-09-29 08:00 UTC, adamskrodzki commented
resolve conflicts

2022-09-30 13:12 UTC, halaprix commented on contracts/AutomationBot.sol
> +                0x0000000000000000000000000000000000000000,
✅

2022-09-30 13:12 UTC, halaprix commented on contracts/AutomationBot.sol
>          uint256 daiCoverage
✅

2022-09-30 13:13 UTC, halaprix commented on contracts/adapters/MakerAdapter.sol
> +        address,
✅

2022-09-30 13:23 UTC, halaprix commented on contracts/AutomationBot.sol
> +            IAdapter adapter = IAdapter(getAdapterAddress(1));
it was a duplicate - `permit` removed from `removeTrigger`

2022-09-30 13:43 UTC, adamskrodzki approved these changes

2022-09-30 13:48 UTC, adamskrodzki requested changes
resolve conflicts

2022-09-30 14:19 UTC, merged