fix `5.21 Unused Parameter, Variable and Event`
OasisDEX/automation-smartcontracts pull request #159
Opened 2023-01-13 10:38 UTC by halaprix

2023-01-16 14:23 UTC, adamskrodzki requested changes

2023-01-16 14:23 UTC, adamskrodzki commented on contracts/adapters/AAVEAdapter.sol
> +contract AAVEAdapter is IAdapter {
https://github.com/OasisDEX/automation-smartcontracts/pull/161

proposal of different approach

2023-01-16 14:23 UTC, adamskrodzki commented on contracts/adapters/AAVEAdapter.sol
> +    function canCall(bytes memory, address) external virtual returns (bool) {}
remove it or at best revert inside if code is not functional

2023-01-16 14:23 UTC, adamskrodzki commented on contracts/adapters/DPMAdapter.sol
> +contract DPMAdapter is IAdapter {
https://github.com/OasisDEX/automation-smartcontracts/pull/161

2023-01-16 14:23 UTC, adamskrodzki commented on contracts/adapters/MakerAdapter.sol
> +contract MakerAdapter is IAdapter {
https://github.com/OasisDEX/automation-smartcontracts/pull/161

2023-01-16 14:23 UTC, adamskrodzki commented on test/automation-bot.ts
> +        it.only('should emit TriggerAdded if called by user being an owner of proxy and the id[0] is == 1', async () => {
remove only

2023-01-16 15:06 UTC, halaprix commented on contracts/AutomationBot.sol
> -    event ApprovalGranted(bytes indexed triggerData, address approvedEntity);
added

2023-01-16 15:07 UTC, halaprix commented on test/automation-bot.ts
> +        it.only('should emit TriggerAdded if called by user being an owner of proxy and the id[0] is == 1', async () => {
done

2023-01-18 12:15 UTC, adamskrodzki approved these changes

2023-01-18 12:23 UTC, merged