upgrade ServiceRegistry
OasisDEX/automation-smartcontracts pull request #179
Opened 2023-03-03 13:15 UTC by adamskrodzki

2023-03-07 08:37 UTC, halaprix commented on test/automation-bot.ts
> +        describe.skip('command update', async () => {
I'd remove the test since update of the command will not be possible.
Unless we go for a different solution with command versioning

2023-03-07 08:41 UTC, halaprix requested changes
comment

2023-03-10 12:49 UTC, adamskrodzki commented on test/service-registry.ts
>          const supposedHash = '0x86f0bcd06cf4f76528c1c306ce9a4dbdae9657972fbb868243c4f564b79e6209'
those are meaningless values just for the purpose of tests

2023-03-10 13:06 UTC, halaprix approved these changes

2023-03-10 13:35 UTC, merged